/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortForwardingRouteImport } from './routes/port-forwarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HostsNewRouteImport } from './routes/hosts.new'
import { Route as ForwardsNewRouteImport } from './routes/forwards.new'
import { Route as HostsEditHostIdRouteImport } from './routes/hosts.edit.$hostId'
import { Route as ForwardsEditForwardIdRouteImport } from './routes/forwards.edit.$forwardId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortForwardingRoute = PortForwardingRouteImport.update({
  id: '/port-forwarding',
  path: '/port-forwarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsNewRoute = HostsNewRouteImport.update({
  id: '/hosts/new',
  path: '/hosts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ForwardsNewRoute = ForwardsNewRouteImport.update({
  id: '/forwards/new',
  path: '/forwards/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsEditHostIdRoute = HostsEditHostIdRouteImport.update({
  id: '/hosts/edit/$hostId',
  path: '/hosts/edit/$hostId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForwardsEditForwardIdRoute = ForwardsEditForwardIdRouteImport.update({
  id: '/forwards/edit/$forwardId',
  path: '/forwards/edit/$forwardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/port-forwarding': typeof PortForwardingRoute
  '/settings': typeof SettingsRoute
  '/forwards/new': typeof ForwardsNewRoute
  '/hosts/new': typeof HostsNewRoute
  '/forwards/edit/$forwardId': typeof ForwardsEditForwardIdRoute
  '/hosts/edit/$hostId': typeof HostsEditHostIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/port-forwarding': typeof PortForwardingRoute
  '/settings': typeof SettingsRoute
  '/forwards/new': typeof ForwardsNewRoute
  '/hosts/new': typeof HostsNewRoute
  '/forwards/edit/$forwardId': typeof ForwardsEditForwardIdRoute
  '/hosts/edit/$hostId': typeof HostsEditHostIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/port-forwarding': typeof PortForwardingRoute
  '/settings': typeof SettingsRoute
  '/forwards/new': typeof ForwardsNewRoute
  '/hosts/new': typeof HostsNewRoute
  '/forwards/edit/$forwardId': typeof ForwardsEditForwardIdRoute
  '/hosts/edit/$hostId': typeof HostsEditHostIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/port-forwarding'
    | '/settings'
    | '/forwards/new'
    | '/hosts/new'
    | '/forwards/edit/$forwardId'
    | '/hosts/edit/$hostId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/port-forwarding'
    | '/settings'
    | '/forwards/new'
    | '/hosts/new'
    | '/forwards/edit/$forwardId'
    | '/hosts/edit/$hostId'
  id:
    | '__root__'
    | '/'
    | '/port-forwarding'
    | '/settings'
    | '/forwards/new'
    | '/hosts/new'
    | '/forwards/edit/$forwardId'
    | '/hosts/edit/$hostId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortForwardingRoute: typeof PortForwardingRoute
  SettingsRoute: typeof SettingsRoute
  ForwardsNewRoute: typeof ForwardsNewRoute
  HostsNewRoute: typeof HostsNewRoute
  ForwardsEditForwardIdRoute: typeof ForwardsEditForwardIdRoute
  HostsEditHostIdRoute: typeof HostsEditHostIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/port-forwarding': {
      id: '/port-forwarding'
      path: '/port-forwarding'
      fullPath: '/port-forwarding'
      preLoaderRoute: typeof PortForwardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/new': {
      id: '/hosts/new'
      path: '/hosts/new'
      fullPath: '/hosts/new'
      preLoaderRoute: typeof HostsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forwards/new': {
      id: '/forwards/new'
      path: '/forwards/new'
      fullPath: '/forwards/new'
      preLoaderRoute: typeof ForwardsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts/edit/$hostId': {
      id: '/hosts/edit/$hostId'
      path: '/hosts/edit/$hostId'
      fullPath: '/hosts/edit/$hostId'
      preLoaderRoute: typeof HostsEditHostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forwards/edit/$forwardId': {
      id: '/forwards/edit/$forwardId'
      path: '/forwards/edit/$forwardId'
      fullPath: '/forwards/edit/$forwardId'
      preLoaderRoute: typeof ForwardsEditForwardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortForwardingRoute: PortForwardingRoute,
  SettingsRoute: SettingsRoute,
  ForwardsNewRoute: ForwardsNewRoute,
  HostsNewRoute: HostsNewRoute,
  ForwardsEditForwardIdRoute: ForwardsEditForwardIdRoute,
  HostsEditHostIdRoute: HostsEditHostIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
